### ISSUE TITLE
UnicodeDecodeError when using drawing order

### ISSUE THREAD

**Issue by pka** [qgiscloud/qgis-cloud-plugin#2]
When layer drawing order is used, a client side exception happens when uploading the project:

```
GISCloud exception: Error uploading project
Traceback (most recent call last): 
  File "C:/Dokumente und Einstellungen/user/.qgis//python/plugins\qgiscloud\qgiscloudplugindialog.py", line 255, in publish_map
    map = self.api.create_map(self.map(), fname, config)['map'] 
  File "C:/Dokumente und Einstellungen/user/.qgis//python/plugins\qgiscloud\qgiscloudapi\qgiscloudapi.py", line 253, in create_map
    content = request.post(resource, data) 
  File "C:/Dokumente und Einstellungen/user/.qgis//python/plugins\qgiscloud\qgiscloudapi\qgiscloudapi.py", line 562, in post
    return self.request(resource, method='POST', data=data) 
  File "C:/Dokumente und Einstellungen/user/.qgis//python/plugins\qgiscloud\qgiscloudapi\qgiscloudapi.py", line 650, in request
    msg = e.read().decode('UTF8') 
  File "C:\OSGeo4W\apps\Python27\lib\encodings\utf_8.py", line 16, in decode 
    return codecs.utf_8_decode(input, errors, True) 
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte 
{'versions': {'QGIS': '1.8.0-Lisboa', 'OS': 'Windows-XP-5.1.2600-SP3', 'plugin': '0.7.4'}}
```

**Comment by hdus** [comment]
This issue is fixed.
