### ISSUE TITLE
access to qgiscloud from Mac's does not seem to be possible

### ISSUE THREAD

**Issue by tpo** [qgiscloud/qgis-cloud-plugin#36]
Users are reporting a stacktrace like this:

<pre>
2019-09-18T16:02:19     WARNING    Traceback (most recent call last):
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/urllib/request.py", line 1317, in do_open encode_chunked=req.has_header('Transfer-encoding'))
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1229, in request self._send_request(method, url, body, headers, encode_chunked)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1275, in _send_request self.endheaders(body, encode_chunked=encode_chunked)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1224, in endheaders self._send_output(message_body, encode_chunked=encode_chunked)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1016, in _send_output self.send(msg)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 956, in send self.connect()
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/http/client.py", line 1392, in connect server_hostname=server_hostname)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/ssl.py", line 412, in wrap_socket session=session
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/ssl.py", line 853, in _create self.do_handshake()
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/ssl.py", line 1117, in do_handshake self._sslobj.do_handshake()
             ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "/Users/joe_user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/qgiscloudplugindialog.py", line 292, in check_login version_info=self._version_info())
              File "/Users/joe_user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/qgiscloudapi/qgiscloudapi.py", line 163, in check_login content = request.post(resource, data)
              File "/Users/joe_user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/qgiscloudapi/qgiscloudapi.py", line 569, in post return self.request(resource, method='POST', data=data)
              File "/Users/joe_user/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/qgiscloudapi/qgiscloudapi.py", line 657, in request response = urllib.request.urlopen(req).read()
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/urllib/request.py", line 525, in open response = self._open(req, data)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/urllib/request.py", line 543, in _open '_open', req)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/urllib/request.py", line 503, in _call_chain result = func(*args)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/urllib/request.py", line 1360, in https_open context=self._context, check_hostname=self._check_hostname)
              File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/urllib/request.py", line 1319, in do_open raise URLError(err)
             urllib.error.URLError
</pre>

**Comment by tpo** [comment]
The following `test.py` program is displaying the same problem:
<pre>
import urllib.request
req = urllib.request.Request('https://api.qgiscloud.com')
with urllib.request.urlopen(req) as response:
    the_page = response.read()
</pre>

<pre>
$ /Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3.7 test.py
Traceback (most recent call last):
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open encode_chunked=req.has_header('Transfer-encoding'))
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request self._send_request(method, url, body, headers, encode_chunked)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request self.endheaders(body, encode_chunked=encode_chunked)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output self.send(msg)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send self.connect()
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect server_hostname=server_hostname)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket session=session
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create self.do_handshake()
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/joe_user/test.py", line 3, in <module> with urllib.request.urlopen(req) as response:
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen return opener.open(url, data, timeout)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open response = self._open(req, data)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open '_open', req)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain result = func(*args)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1360, in https_open context=self._context, check_hostname=self._check_hostname)
  File "/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1319, in do_open raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>
</pre>

**Comment by tpo** [comment]
The installation procedure of python 3.7 is displaying the following text:

<pre>
Certificate verification and OpenSSLThis package includes its own private copy of OpenSSL 1.1.1. The trust certificates in system and user keychainsmanaged by the Keychain Access application andthe security command line utility are not used as defaults by the Python ssl module. A sample command script isincluded in /Applications/Python 3.8 to installa curated bundle of default root certificates from the third-party certifi package (https:// pypi.org/project/certifi/[pypi.org]).Double-clickon Install Certificates to run it.The bundled pip has its own default certificate store for verifying download connections.
</pre>

It is unknown whether the users that have the mentioned connection problem have followed those instructions. Missing a Mac to test on we are currently unable to reproduce the problem.

Help from knowledgeable Mac users would be very appreciated.

**Comment by tpo** [comment]
Here are instruction on how to work around the problem: https://github.com/qgiscloud/qgis-cloud-plugin/wiki/Resolving-certificate-problems-on-OSX

**Comment by tpo** [comment]
This is the same problem as https://github.com/lutraconsulting/mergin-py-client/pull/39 , which contains a workaround in code.

A corresponding ticket has been filled against the [QGIS-Mac-Packager](https://github.com/qgis/QGIS-Mac-Packager/issues/32).
