### ISSUE TITLE
Uploading files fails with 'relation ""public"."layer_name"" does not exist'

### ISSUE THREAD

**Issue by kannes** [qgiscloud/qgis-cloud-plugin#53]
- Sign up for a free account
- Install plugin in QGIS
- Log in
- Load a vector layer (e. g. ne_110m_admin_0_countries as Shapefile)
- Try to upload it to the cloud
- It errors with

relation ""public"."ne_110m_admin_0_countries"" does not exist

```
Traceback (most recent call last):
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/qgiscloudplugindialog.py", line 1165, in upload_data
    self.data_upload.upload(self.db_connections.db(
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/data_upload.py", line 284, in upload
    raise RuntimeError(str(messages))
RuntimeError: relation ""public"."ne_110m_admin_0_countries"" does not exist
```

QGIS: 3.21.0-Master
QGIS-Codeversion: 3f1722d0bbc

**Comment by kamazeuci** [comment]
An error has occurred while executing Python code: 

TypeError: toEncoded(self, options: QUrl.FormattingOptions = QUrl.FullyEncoded): argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/home/josei/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/qgiscloudplugindialog.py", line 1240, in upload_data
    self.data_upload.upload(self.db_connections.db(
  File "/home/josei/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/data_upload.py", line 284, in upload
    raise RuntimeError(str(messages))
RuntimeError: relation ""public"."claro26"" does not exist

relation ""public"."entel26"" does not exist

relation ""public"."entel3500"" does not exist

relation ""public"."telefonica3500"" does not exist

relation ""public"."wom26"" does not exist

relation ""public"."wom3500"" does not exist

relation ""public"."wom700"" does not exist

relation ""public"."womaws"" does not exist



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/josei/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgiscloud/error_report_dialog.py", line 83, in __reportError
    url.toEncoded("mailto:support@qgiscloud.com?subject=%s&body=%s" % (
TypeError: toEncoded(self, options: QUrl.FormattingOptions = QUrl.FullyEncoded): argument 1 has unexpected type 'str'


Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] 
QGIS version: 3.24.3-Tisler Tisler, exported 

Python Path:
/usr/share/qgis/python
/home/josei/.local/share/QGIS/QGIS3/profiles/default/python
/home/josei/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/lib/python3.10/site-packages
/home/josei/.local/share/QGIS/QGIS3/profiles/default/python
/home/josei/Documents/Projects/5G

**Comment by tpo** [comment]
Hi @kamazeuci this is not the QGIS Cloud Support site. Please file a ticket at https://support.qgiscloud.com

**Comment by kannes** [comment]
A crash of the plugin sounds like a good reason to post an issue here though?

**Comment by tpo** [comment]
> A crash of the plugin sounds like a good reason to post an issue here though?

I agree.

**Comment by mwa** [comment]
Fixed in 1f135c2c and included in Release v3.4.3

The issue was caused by an API change for `copy_from()` in psycopg v2.9.x when using DB schema names.
