### ISSUE TITLE
QGIS Cloud Plugin startup error 'QgisCloudPluginDialog' object has no attribute 'maxDBs'

### ISSUE THREAD

**Issue by Les-Searle** [qgiscloud/qgis-cloud-plugin#62]
Upgrade to version 3.8.0 has created a login issue.  I can login to the app using QGIS 3.28.4 however the app does not link my cloud database.  As I am using the free version I am only entitled to one database so I cannot create a new database.

Is it possible to wind back to the previous version.  See error logs below.
```
2023-03-16T14:48:17     WARNING    Python error : Couldn't load plugin 'MetaSearch' due to an error when calling its classFactory() method See message log (Python Error) for more details.
2023-03-16T14:49:05     INFO    Plugin uninstalled successfully
2023-03-16T14:49:45     INFO    Plugin uninstalled successfully
2023-03-16T14:49:54     INFO    Plugin uninstalled successfully
2023-03-16T14:50:09     INFO    Plugin uninstalled successfully
2023-03-16T14:50:19     INFO    Plugin uninstalled successfully
2023-03-16T14:52:09     INFO    QGIS Cloud : Logged in as LesSearle
2023-03-16T14:52:27     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.
2023-03-16T14:48:17     CRITICAL    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins\MetaSearch\__init__.py", line 29, in classFactory
              from MetaSearch.plugin import MetaSearchPlugin
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins\MetaSearch\plugin.py", line 34, in 
              from MetaSearch.dialogs.maindialog import MetaSearchDialog
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins\MetaSearch\dialogs\maindialog.py", line 49, in 
              from MetaSearch.dialogs.newconnectiondialog import NewConnectionDialog
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins\MetaSearch\dialogs\newconnectiondialog.py", line 34, in 
              from MetaSearch.search_backend import CATALOG_TYPES
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python/plugins\MetaSearch\search_backend.py", line 29, in 
              from owslib.fes import BBox, PropertyIsLike
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\owslib\fes.py", line 19, in 
              from owslib import util
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\owslib\util.py", line 26, in 
              import requests
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\requests\__init__.py", line 120, in 
              from . import utils
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\requests\utils.py", line 27, in 
              from ._internal_utils import to_native_string
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\requests\_internal_utils.py", line 11, in 
              from .compat import is_py2, builtin_str, str
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\PROGRA~1\QGIS32~1.4\apps\Python39\lib\site-packages\requests\compat.py", line 29, in 
              import simplejson as json
              File "C:\PROGRA~1/QGIS32~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/Les.Searle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\simplejson\__init__.py", line 100
              __version__ = '2.1.7'
             IndentationError: unexpected indent
             
2023-03-16T14:52:27     WARNING    Traceback (most recent call last):
              File "C:\Users/Les.Searle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\qgiscloudplugindialog.py", line 482, in check_login
              self.create_database()
              File "C:\Users/Les.Searle/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgiscloud\qgiscloudplugindialog.py", line 487, in create_database
              if self.numDbs              AttributeError: 'QgisCloudPluginDialog' object has no attribute 'maxDBs'
```

**Comment by mwa** [comment]
This error was not related to the new plugin version. According to our logs, there were some temporary server issues on 2023-03-16 at this time, so the plugin could not get your list of databases. Thus the missing database list led to the above QGIS Cloud plugin error.

We will try to improve the error handling.

The first error (_... IndentationError: unexpected indent_) seems unrelated to the QGIS Cloud plugin and may have been some side effect from other plugins.
